version: "3.9"
services:
   worker:
    build: .
    environment:
      BOT_TOKEN: 6288965499:AAGfz_Uztf3Vb6ICZr26Ut5vHx7h7JoCpi4
      API_ID: 13036663
      API_HASH: d8f790de6cb092ba5e8065344b349aa8
      CHANNELS: $CHANNELS
      ADMINS: $ADMINS
      LOG_CHANNEL: $LOG_CHANNEL
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_URI: $DATABASE_URI
      HEROKU_API_KEY: $HEROKU_API_KEY
